version: "3"

services:
  frontend:
    image: 03farhan/ect/frontend
    volumes:
      - "./frontend:/frontend"
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    image: 03farhan/ect/backend
    volumes:
      - "./backend:/backend"
    ports:
      - 9000:9000
    environment:
      - CHOKIDAR_USEPOLLING=true
